INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');

INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');

INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');

INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out de 8:00 a 11:00Hs, Prohibido fumar, Prohibidas las reuniones con terceros', 'Control de certificado de vacunacion, Uso de barbijo obligatorio en espacios comunes, Deposito de seguridad ', 'Reserva minima 3 noches, Cancelacion reembolsable unicamente abonando con tarjeta de débito');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check in desde 10:00Hs, Check out de 06:00 a 09:00, Se prohiben las mascotas ', 'Control de temperatura y vacunacion, Predio vigilado 24/7, Caja fuerte', 'Reserva minima de 2 noches, Reembolso disponible unicamente abonando con tarjeta de debito y con 3 dias de anticipacion al Check in');
INSERT INTO `digital_booking_db`.`politicas`(normas, saludyseguridad, cancelacion) VALUES('Check out 10:00Hs, Prohibido fumar, Prohibidas las mascotas', 'Control de vacunacion, Caja fuerte, Detector de humo', 'Reserva minima 3 dias, Cancelacion con reembolso con 7 dias de anticipacion al Check in');
