DROP SCHEMA IF EXISTS `ti_db`;
CREATE SCHEMA IF NOT EXISTS `ti_db`
DEFAULT CHARACTER SET `utf8mb4`
DEFAULT COLLATE `utf8mb4_0900_ai_ci`;

CREATE TABLE IF NOT EXISTS `ti_db`.`Ciudades` (
  `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `Nombre` VARCHAR(127) NOT NULL,
  `Pais` VARCHAR(63) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ti_db`.`Categorias` (
  `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `Titulo` VARCHAR(127) NOT NULL,
  `Descripcion` VARCHAR(255) DEFAULT NULL,
  `URL_Imagen` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ti_db`.`Caracteristicas` (
  `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `Nombre` VARCHAR(127) NOT NULL,
  `Icono` VARCHAR(127) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ti_db`.`Productos` (
  `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `Nombre` VARCHAR(127) NOT NULL,
  `Descripcion` VARCHAR(255) DEFAULT NULL,
  `Categoria_ID` BIGINT NOT NULL,
  `Ciudad_ID` BIGINT NOT NULL,
  CONSTRAINT FK_Productos_Categorias FOREIGN KEY (Categoria_ID) REFERENCES Categorias(ID),
  CONSTRAINT FK_Productos_Ciudades FOREIGN KEY (Ciudad_ID) REFERENCES Ciudades(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ti_db`.`Imagenes` (
  `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `Titulo` VARCHAR(127) NOT NULL,
  `URL` VARCHAR(255) DEFAULT NULL,
  `Producto_ID` BIGINT NOT NULL,
  CONSTRAINT FK_Imagenes_Productos FOREIGN KEY (Producto_ID) REFERENCES Productos(ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `ti_db`.`Productos_X_Caracteristicas` (
  `ID` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `Producto_ID` BIGINT NOT NULL,
  `Caracteristica_ID` BIGINT NOT NULL,
  CONSTRAINT FK_Productos_X_Caracteristicas_Productos FOREIGN KEY (Producto_ID) REFERENCES Productos(ID),
  CONSTRAINT FK_Productos_X_Caracteristicas_Caracteristicas FOREIGN KEY (Caracteristica_ID) REFERENCES Caracteristicas(ID)
) ENGINE=InnoDB;