INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('ibis Cartagena Marbella', 'El Ibis Cartagena Marbella ofrece un bar y habitaciones con aire acondicionado en Cartagena de Indias, a 2,8 km del Museo de Arte Moderno de Cartagena.', '1', '1', '10.436937073115532', '-75.53564307317058');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('GHL Corales de Indias', 'El GHL Corales De Indias se encuentra en Cartagena de Indias y ofrece piscina al aire libre y restaurante. Dispone de habitaciones amplias y modernas con TV de pantalla plana y aire acondicionado. Todas cuentan con escritorio y vistas impresionantes al oc', '1', '1', '10.443387335873695', '-75.52558259293589');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Fragata Island House', 'El Fragata Island House se encuentra en Cartagena de Indias, a 2,7 km de Playa Libre. Ofrece alojamiento frente a la playa, restaurante, bar y zona de playa privada. Las habitaciones disponen de baño privado y TV de pantalla plana vía satélite. El alojami', '2', '1', '10.176009837660903', '-75.7566463969151');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Casa de la Cruz', 'La Casa de la Cruz se encuentra en Cartagena de Indias, a 700 metros de la playa de Marbella, y ofrece alojamiento con aire acondicionado y bar. Además, tiene terraza y cocina compartida. Hay WiFi gratuita y se facilita aparcamiento privado por un supleme', '2', '1', '10.426159636627805', '-75.54659637317067');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Travelers Orange Cartagena', 'El Orange Cartagena ofrece conexión inalámbrica a internet gratuita, una piscina exterior y un alojamiento amplio. Todos los apartamentos disponen de un balcón con zona de estar. Todos los apartamentos del Orange Cartagena tienen una cocina y están equipa', '3', '1','10.394987605807657', '-75.55150400200674');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Ganem Suites Cartagena', 'El Ganem Suites Cartagena ofrece alojamiento con aire acondicionado en el centro de Cartagena de Indias, a 300 metros del Museo del Oro de Cartagena, a 300 metros del parque Bolívar y a menos de 1 km de la playa de Marbella. El apartamento dispone de zona', '3', '1','10.42633242631221', '-75.54944713084247');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('MAR uno', 'El MAR uno ofrece jardín y aire acondicionado y se encuentra en Cartagena de Indias, a 1,5 km de la playa de Marbella y a 3,5 km de la escalera del cerro de La Popa. Este establecimiento situado frente a la playa ofrece acceso a un balcón, aparcamiento pr', '4', '1', '10.440209316891549', '-75.52376034433476');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('CASA BARBACOA BEACH', 'La CASA BARBACOA BEACH ofrece una piscina al aire libre y una recepción abierta las 24 horas en una ubicación privilegiada en Cartagena de Indias, a 2,7 km de Playa Blanca y a 23 km del Palacio de la Inquisición. Esta casa cuenta con piscina privada, jard', '4', '1', '10.22126437121742', '-75.58262771549944');

INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Hotel Bogotá Regency Usaquén', 'El Bogotá Regency se encuentra en el tradicional barrio Usaquén de Bogotá, a 1,5 km del centro comercial Unicentro. Todas las habitaciones tienen TV por cable de pantalla plana y WiFi gratuita. El restaurante del establecimiento prepara una variedad de pl', '1', '2', '4.702843543629587', '-74.02898591550453');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Sary House', 'El Sary House se encuentra en Bogotá, a 4,3 km de la Zona T y a 4,4 km del centro comercial Unicentro, y ofrece alojamiento con terraza y aparcamiento privado gratuito. Cuenta con recepción 24 horas, cocina compartida y WiFi gratuita en todas las instalac', '2', '2', '4.686043163096417', '-74.04980781550454');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('The Palma Home', 'El The Palma Home se encuentra en Bogotá, a 6 km del centro comercial Unicentro y a 10 km de la Zona T, y ofrece alojamiento con jardín, WiFi gratuita en todas las instalaciones y aparcamiento privado gratuito. Ofrece habitaciones familiares y terraza. La', '2', '2', '4.737182101253798', '-74.04214731735593');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('100 Luxury Suites by Preferred', 'El 100 Luxury Suites alberga un restaurante y un restaurante a la carta y ofrece apartamentos modernos en Bogotá, a solo 10 minutos a pie del famoso parque de la 93. Hay WiFi gratuita. Los apartamentos cuentan con una habitación amplia, cocina totalmente ', '3', '2', '10.221327722614753', '-75.58264917317126');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Cassa Luxury Homes', 'El alojamiento Cassa Luxury Homes está situado a 1,2 km de la Zona T y cuenta con restaurante, bar, piscina al aire libre y centro de fitness. Hay WiFi gratuita en todas las zonas. Todos los alojamientos tienen zona de estar, TV de pantalla plana vía saté', '3', '2', '4.673695132514192', '-74.05657901365312');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('La casa de Leo', 'La casa de Leo ofrece alojamiento con balcón en Bogotá. La casa, ubicada en un edificio que data de 2009, se encuentra a 7 km del estadio El Campín y a 8 km del centro internacional de exposiciones Corferias. La casa cuenta con 3 dormitorios, TV de pantal', '4', '2', '4.6775551317534125', '-74.05618217205183');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('House Centrik', 'El Centrik ofrece alojamiento con terraza en Bogotá, a menos de 1 km del centro comercial Unicentro y a 3,3 km de la Zona T. Esta casa se encuentra a 7 km del estadio El Campín y a 9 km del cerro Monserrate. La casa cuenta con TV de pantalla plana y 1 dor', '4', '2', '4.621045206052734', '-74.09852582661257');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('GH Laurel Casa Ale', 'In the Candelaria - Centro Historico district of Bogotá, close to Quevedos Jet, GH Laurel Casa Ale features free WiFi and a washing machine. The property has mountain views and is 400 metres from Luis Angel Arango Library and 800 metres from Bolivar Square.', '1', '2', '4.594056144596313', '-74.07020761550436');

INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Design Suites Buenos Aires', 'Este establecimiento está situado a 700 metros de la Plaza de Mayo. El Design Suites Buenos Aires cuenta con spa, piscina cubierta climatizada, sauna, centro de fitness y un bar donde se sirve un desayuno cada mañana. También tiene WiFi gratuita. Las habi', '1', '8','-34.61100678774418', '-58.37925018619244');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('DEL900 Hostel Boutique', 'El establecimiento DEL900 Hostel Boutique está ubicado en Buenos Aires, a 50 metros de la Avenida de Mayo, y ofrece WiFi gratuita y zona de barbacoa. El establecimiento alberga un bar y una sala de juegos. Las habitaciones incluyen aire acondicionado, esc', '1', '8', '-34.60956973296248', '-58.38355691687963');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Baires House', 'El Baires House está situado a 1,5 km del Obelisco de Buenos Aires y ofrece conexión Wi-Fi gratuita. Todos los alojamientos disponen de aire acondicionado y TV de pantalla plana por un suplemento. Algunos alojamientos tienen terraza y/o balcón. Los huéspe', '2', '8', '-34.60601323680034', '-58.39502143037202');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Avenida Tango', 'El Avenida Tango goza de una buena ubicación en el distrito de Monserrat de Buenos Aires, a pocos pasos del Palacio Barolo, a 1,1 km del Tortoni Cafe y a 1,4 km del Obelisco de Buenos Aires. El establecimiento se encuentra a unos 1,6 km del teatro Colón, ', '2', '8', '-34.61178643041294', '-58.38756444293282');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Up Viamonte Hotel', 'El Up Viamonte Hotel, situado a solo 150 metros de la famosa Ópera Colón, ofrece habitaciones independientes con aire acondicionado y conexión WiFi gratuita en el centro de Buenos Aires. También cuenta con restaurante. El Obelisco está a 200 metros del es', '3', '8', '-34.60017643000253', '-58.386303286192614');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('TPYN Palermo', 'El TPYN Palermo ofrece vistas a la ciudad, terraza y WiFi gratuita y se encuentra en Buenos Aires, a poca distancia de Palermo Lakes, el parque ecológico de Buenos Aires y el parque El Rosedal. El alojamiento cuenta con bañera de hidromasaje. El alojamien', '3', '8', '-34.57751947419518', '-58.42415937270087');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Casa quinta Los Alazanes', 'La Casa quinta Los Alazanes se encuentra en Buenos Aires y ofrece alojamiento con aire acondicionado y piscina privada. La casa tiene vistas a la piscina y está a 34 km de Campana. La casa cuenta con 1 dormitorio, TV de pantalla plana con canales vía saté', '4', '8', '-34.56954825541087', '-58.47446721502915');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Soho Point Homes', 'El Soho Point Homes se encuentra en Buenos Aires, a menos de 1 km de la plaza Serrano y a 1,8 km del parque ecológico de Buenos Aires, y ofrece alojamiento con WiFi gratuita, aire acondicionado, jardín y zona de barbacoa. Los alojamientos disponen de zona', '4', '8', '-34.585738357122494', '-58.42646994386488');

INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('NH Córdoba Panorama', 'El NH Panorama ofrece alojamiento elegante en la zona de Cañada, en el centro de Córdoba. Dispone de piscina en la azotea con vistas panorámicas a la ciudad, spa, gimnasio y un restaurante de 1ª calidad. También incluye conexión WiFi gratuita. Las habitaciones del NH Panorama presentan interiores elegantes con muebles modernos. Todas están equipadas con aire acondicionado y TV por cable. Algunas cuentan con balcón privado, bañera de hidromasaje y TV LCD.', '1', '5', '-31.41645870550038', '-64.19061508626191');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Santiago Hotel', 'El Santiago Hotel alberga bar y piscina exterior y está situado a solo 300 metros del centro cívico de Córdoba. Ofrece desayuno todos los días y WiFi gratuita. Las habitaciones incluyen escritorio, TV de pantalla plana y baño completo con artículos de aseo gratuitos. También ofrecen armario, escritorio, aire acondicionado y calefacción. Se ofrecen habitaciones comunicadas', '1', '5', '-31.416212324978684', '-64.17700531694918');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('HA! Residencia 2', 'El HA! La Residencia 2 in Cordoba ofrece alojamiento solo para adultos con zona de barbacoa y terraza. El establecimiento se encuentra a 2 km de la Manzana Jesuítica, a 2,1 km de la catedral de Córdoba y a 3 km del centro cívico de Córdoba. El alojamiento cuenta con cocina compartida, salón compartido y servicio de cambio de divisa. Las habitaciones tienen baño compartido y WiFi gratuita.', '2', '5', '-31.417362566330223', '-64.19570411509788');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('La casa de Marta', 'La casa demarta dispone de jardín y piscina exterior de temporada y está situada en Córdoba, a 1,3 km del estadio de fútbol Mario Alberto Kempes y a 3,7 km del centro comercial Córdoba. El establecimiento se encuentra a 9 km del centro comercial Patio Olmos, a 9 km de la Manzana Jesuítica y a 9 km de la catedral de Córdoba. El establecimiento cuenta con habitaciones familiares. Todas las habitaciones están equipadas con armario, TV de pantalla plana, baño privado, ropa de cama y toallas. Todos los alojamientos de La casa demarta están equipados con zona de estar.', '2', '6', '-31.90526839838679', '-64.57717285741558');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Balcarce Deluxe', 'El Balcarce Deluxe ofrece apartamentos independientes con conexión WiFi gratuita en Córdoba. El establecimiento se encuentra a 200 metros de la estación de autobús, a 500 metros del centro cultural, recreativo y comercial "Paseo del Buen Pastor" y a 300 metros de la "Milla de los Museos". Este establecimiento está rodeado de numerosas tiendas, bares y restaurantes. Los apartamentos, totalmente amueblados, disponen de aire acondicionado, calefacción, TV LCD de pantalla plana, 1 cama doble con colchón con somier, y un sofá cama.', '3', '6', '-31.42479953293248', '-64.17898367276946');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('King David Flat Hotel - Argentina', 'El King David Flat Hotel ofrece apartamentos independientes con conexión Wi-Fi gratuita en Córdoba. Cuenta con una piscina en la azotea, un gimnasio recién reformado y un restaurante. Se halla a 600 metros de la plaza San Martín y sirve desayunos. Los apartamentos del King David Flat están decorados con muebles de madera clara y suelo de parqué y disponen de zona de comedor, microondas y nevera. Todos los días se sirve un desayuno bufé. El restaurante elabora una amplia variedad de platos regionales e internacionales, mientras que el bar ofrece bebidas y aperitivos.', '3', '7', '-31.410753367662306', '-64.18470890160575');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('Casa Alberdi', 'La Casa Alberdi ofrece jardín y aire acondicionado y se encuentra en Córdoba, a 3,8 km del centro comercial Patio Olmos y a 4 km de la plaza de España. Esta casa dispone de aparcamiento privado gratuito, recepción 24 horas y conexión WiFi gratuita. La casa cuenta con 1 dormitorio, 1 baño, ropa de cama, toallas, TV de pantalla plana con canales por cable, zona de comedor, cocina totalmente equipada y patio con vistas al jardín. El establecimiento proporciona toallas y ropa de cama por un suplemento.', '4', '7', '-31.540406267025237', '-68.53014071509523');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud) VALUES('RIO y VERDE', 'El RIO y VERDE se encuentra en Córdoba, a 2,3 km del centro comercial Córdoba y a 6 km del estadio de fútbol Mario Alberto Kempes, y ofrece piscina exterior de temporada y aire acondicionado. Esta casa cuenta con piscina privada, jardín, zona de barbacoa, WiFi gratuita y aparcamiento privado gratuito. La casa tiene 3 dormitorios, 2 baños, ropa de cama, toallas, TV de pantalla plana con canales por cable, zona de comedor, cocina totalmente equipada y patio con vistas a la piscina.', '4', '7', '-31.950103398506233', '-65.05408849007746');