INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id ) VALUES('ibis Cartagena Marbella', 'D T, Cra. 1 ##47-90, Cartagena de Indias, Provincia de Cartagena, Bolívar, Colombia', 'El Ibis Cartagena Marbella ofrece un bar y habitaciones con aire acondicionado en Cartagena de Indias, a 2,8 km del Museo de Arte Moderno de Cartagena.', '1', '1', '10.436937073115532', '-75.53564307317058', '1');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('GHL Corales de Indias', ' Cra. 1 #No. 62-198, Cartagena de Indias, Provincia de Cartagena, Bolívar, Colombia', 'El GHL Corales De Indias se encuentra en Cartagena de Indias y ofrece piscina al aire libre y restaurante. Dispone de habitaciones amplias y modernas con TV de pantalla plana y aire acondicionado.', '1', '1', '10.443387335873695', '-75.52558259293589', '2');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Fragata Island House', 'Islas del Rosario, Bolívar, Colombia', 'El Fragata Island House se encuentra en Cartagena de Indias, a 2,7 km de Playa Libre. Ofrece alojamiento frente a la playa, restaurante, bar y zona de playa privada. Las habitaciones disponen de baño privado y TV de pantalla plana vía satélite.', '2', '1', '10.176009837660903', '-75.7566463969151', '3');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Casa de la Cruz', 'calle 36 (Calle de la Cruz) No 9-73 Barrio San Diego Centro Historico, San Diego', 'La Casa de la Cruz se encuentra en Cartagena de Indias, a 700 metros de la playa de Marbella, y ofrece alojamiento con aire acondicionado y bar. Además, tiene terraza y cocina compartida.', '2', '1', '10.426159636627805', '-75.54659637317067', '4');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Travelers Orange Cartagena', 'Cra. 10 ##No. 5A-15, Cartagena de Indias, Provincia de Cartagena, Bolívar, Colombia', 'El Orange Cartagena ofrece conexión inalámbrica a internet gratuita, una piscina exterior y un alojamiento amplio. Todos los apartamentos disponen de un balcón con zona de estar.', '3', '1','10.394987605807657', '-75.55150400200674', '5');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Ganem Suites Cartagena', 'Centro Histórico, Cra. 6 # 36-177 Edificio Salomón Ganem, Cartagena de Indias, Bolívar, Colombia', 'El Ganem Suites Cartagena ofrece alojamiento con aire acondicionado en el centro de Cartagena de Indias, a 300 metros del Museo del Oro de Cartagena, a 300 metros del parque Bolívar y a menos de 1 km de la playa de Marbella.', '3', '1','10.42633242631221', '-75.54944713084247', '6');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('MAR uno', 'Cra. 15 ##6334, Cartagena de Indias, Provincia de Cartagena, Bolívar, Colombia', 'El MAR uno ofrece jardín y aire acondicionado y se encuentra en Cartagena de Indias, a 1,5 km de la playa de Marbella y a 3,5 km de la escalera del cerro de La Popa.', '4', '1', '10.440209316891549', '-75.52376034433476', '7');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Casa Barbacoa Beach', 'Vía a Barú, Provincia de Cartagena, Bolívar, Colombia', 'La CASA BARBACOA BEACH ofrece una piscina al aire libre y una recepción abierta las 24 horas en una ubicación privilegiada en Cartagena de Indias, a 2,7 km de Playa Blanca y a 23 km del Palacio de la Inquisición.', '4', '1', '10.22126437121742', '-75.58262771549944', '8');

INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Hotel Bogotá Regency Usaquén', 'Ak. 7 #127 - 21, Bogotá, Colombia', 'El Bogotá Regency se encuentra en el tradicional barrio Usaquén de Bogotá, a 1,5 km del centro comercial Unicentro. Todas las habitaciones tienen TV por cable de pantalla plana y WiFi gratuita.', '1', '2', '4.702843543629587', '-74.02898591550453', '9');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Sary House', 'Ac. 100 #1666, Bogotá, Colombia', 'El Sary House se encuentra en Bogotá, a 4,3 km de la Zona T y a 4,4 km del centro comercial Unicentro, y ofrece alojamiento con terraza y aparcamiento privado gratuito. Cuenta con recepción 24 horas, cocina compartida y WiFi gratuita.', '2', '2', '4.686043163096417', '-74.04980781550454', '10');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('The Palma Home', 'Cl. 154 ##17-04, Bogotá, Colombia', 'El The Palma Home se encuentra en Bogotá, a 6 km del centro comercial Unicentro y a 10 km de la Zona T, y ofrece alojamiento con jardín, WiFi gratuita en todas las instalaciones y aparcamiento privado gratuito. Ofrece habitaciones familiares y terraza.', '2', '2', '4.737182101253798', '-74.04214731735593', '11');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('100 Luxury Suites by Preferred', 'Cra. 9a #98-3, Bogotá, Colombia', 'El 100 Luxury Suites alberga un restaurante y un restaurante a la carta y ofrece apartamentos modernos en Bogotá, a solo 10 minutos a pie del famoso parque de la 93. Hay WiFi gratuita. Los apartamentos cuentan con una habitación amplia, cocina totalmente equipada, zona de estar y un gran armario. También hay una terraza compartida con vistas a la ciudad. El 100 Luxury Suites ofrece recepción 24 horas y un bar. También se ofrecen instalaciones para reuniones, mostrador de información turística y consigna de equipaje.', '3', '2', '10.221327722614753', '-75.58264917317126', '12');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Cassa Luxury Homes', 'Cl. 87 #19 - 21, Bogotá, Colombia', 'El alojamiento Cassa Luxury Homes está situado a 1,2 km de la Zona T y cuenta con restaurante, bar, piscina al aire libre y centro de fitness. Hay WiFi gratuita en todas las zonas.', '3', '2', '4.673695132514192', '-74.05657901365312', '13');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('La casa de Leo', 'C. San Ildefonso, 12, 03001 Alicante, España', 'La casa de Leo ofrece alojamiento con balcón en Bogotá. La casa, ubicada en un edificio que data de 2009, se encuentra a 7 km del estadio El Campín y a 8 km del centro internacional de exposiciones Corferias.', '4', '2', '4.6775551317534125', '-74.05618217205183', '14');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('House Centrik', '11241 Carrera 14A, Usaquén, 110111 Bogotá, Colombia', 'El Centrik ofrece alojamiento con terraza en Bogotá, a menos de 1 km del centro comercial Unicentro y a 3,3 km de la Zona T. Esta casa se encuentra a 7 km del estadio El Campín y a 9 km del cerro Monserrate.', '4', '2', '4.621045206052734', '-74.09852582661257', '15');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('GH Laurel Casa Ale', 'Calle 10, La Candelaria - Centro histórico, 111711 Bogotá, Colombi', 'In the Candelaria - Centro Historico district of Bogotá, close to Quevedos Jet, GH Laurel Casa Ale features free WiFi and a washing machine.', '1', '2', '4.594056144596313', '-74.07020761550436', '16');

INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Design Suites Buenos Aires', 'Marcelo T de Alvear, 1683, Recoleta, C1060AAE Buenos Aires, Argentina', 'Este establecimiento está situado a 700 metros de la Plaza de Mayo. El Design Suites Buenos Aires cuenta con spa, piscina cubierta climatizada, sauna, centro de fitness y un bar donde se sirve un desayuno cada mañana. También tiene WiFi gratuita.', '1', '5','-34.61100678774418', '-58.37925018619244', '17');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('DEL900 Hostel Boutique', 'Hipólito Yrigoyen 1208, Montserrat, 1086 Buenos Aires, Argentina', 'El establecimiento DEL900 Hostel Boutique está ubicado en Buenos Aires, a 50 metros de la Avenida de Mayo, y ofrece WiFi gratuita y zona de barbacoa. El establecimiento alberga un bar y una sala de juegos.', '1', '5', '-34.60956973296248', '-58.38355691687963', '18');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Baires House', 'Ayacucho 277, C1025 Congreso, Buenos Aires', 'El Baires House está situado a 1,5 km del Obelisco de Buenos Aires y ofrece conexión Wi-Fi gratuita. Todos los alojamientos disponen de aire acondicionado y TV de pantalla plana por un suplemento. Algunos alojamientos tienen terraza y/o balcón.', '2', '5', '-34.60601323680034', '-58.39502143037202', '19');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Avenida Tango', '1360 Avenida de Mayo 5ª A, Monserrat, C1085ABQ Buenos Aires, Argentina', 'El Avenida Tango goza de una buena ubicación en el distrito de Monserrat de Buenos Aires, a pocos pasos del Palacio Barolo, a 1,1 km del Tortoni Cafe y a 1,4 km del Obelisco de Buenos Aires.', '2', '5', '-34.61178643041294', '-58.38756444293282', '20');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Up Viamonte Hotel', 'Viamonte 1373, C1053 CABA', 'El Up Viamonte Hotel, situado a solo 150 metros de la famosa Ópera Colón, ofrece habitaciones independientes con aire acondicionado y conexión WiFi gratuita en el centro de Buenos Aires. También cuenta con restaurante.', '3', '5', '-34.60017643000253', '-58.386303286192614', '21');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('TPYN Palermo', 'Beruti 4597, C1425BDC CABA', 'El TPYN Palermo ofrece vistas a la ciudad, terraza y WiFi gratuita y se encuentra en Buenos Aires, a poca distancia de Palermo Lakes, el parque ecológico de Buenos Aires y el parque El Rosedal. El alojamiento cuenta con bañera de hidromasaje.', '3', '5', '-34.57751947419518', '-58.42415937270087', '22');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Casa quinta Los Alazanes', 'El Molino, Escalada, Provincia de Buenos Aires', 'La Casa quinta Los Alazanes se encuentra en Buenos Aires y ofrece alojamiento con aire acondicionado y piscina privada. La casa tiene vistas a la piscina y está a 34 km de Campana.', '4', '5', '-34.56954825541087', '-58.47446721502915', '23');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Soho Point Homes', 'Soler 4830, C1425BXH CABA', 'El Soho Point Homes se encuentra en Buenos Aires, a menos de 1 km de la plaza Serrano y a 1,8 km del parque ecológico de Buenos Aires, y ofrece alojamiento con WiFi gratuita, aire acondicionado, jardín y zona de barbacoa.', '4', '5', '-34.585738357122494', '-58.42646994386488', '24');

INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('NH Córdoba Panorama', 'Av. Marcelo T. de Alvear 251, X5000KGE Córdoba', 'El NH Panorama ofrece alojamiento elegante en la zona de Cañada, en el centro de Córdoba. Dispone de piscina en la azotea con vistas panorámicas a la ciudad, spa, gimnasio y un restaurante de 1ª calidad. También incluye conexión WiFi gratuita.', '1', '6', '-31.41645870550038', '-64.19061508626191', '25');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Santiago Hotel', 'Santiago del Estero 129, X5022 Córdoba', 'El Santiago Hotel alberga bar y piscina exterior y está situado a solo 300 metros del centro cívico de Córdoba. Ofrece desayuno todos los días y WiFi gratuita. Las habitaciones incluyen escritorio, TV de pantalla plana y baño completo con artículos de aseo gratuitos.', '1', '6', '-31.416212324978684', '-64.17700531694918', '26');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('HA! Residencia 2', 'Pje. Sto Tomás 354, Córdoba', 'El HA! La Residencia 2 in Cordoba ofrece alojamiento solo para adultos con zona de barbacoa y terraza. El establecimiento se encuentra a 2 km de la Manzana Jesuítica, a 2,1 km de la catedral de Córdoba y a 3 km del centro cívico de Córdoba.', '2', '6', '-31.417362566330223', '-64.19570411509788', '27');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('La casa de Marta', '5255 Blas Pascal, 5000 Córdoba, Argentina', 'La casa demarta dispone de jardín y piscina exterior de temporada y está situada en Córdoba, a 1,3 km del estadio de fútbol Mario Alberto Kempes y a 3,7 km del centro comercial Córdoba.', '2', '6', '-31.90526839838679', '-64.57717285741558', '28');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Balcarce Deluxe', 'Balcarce 570, X5000 HWL, Córdoba', 'El Balcarce Deluxe ofrece apartamentos independientes con conexión WiFi gratuita en Córdoba. El establecimiento se encuentra a 200 metros de la estación de autobús, a 500 metros del centro cultural, recreativo y comercial "Paseo del Buen Pastor" y a 300 metros de la "Milla de los Museos".', '3', '6', '-31.42479953293248', '-64.17898367276946', '29');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('King David Flat Hotel - Argentina', 'Av. Gral. Paz 386, X5000 JLQ, Córdoba', 'El King David Flat Hotel ofrece apartamentos independientes con conexión Wi-Fi gratuita en Córdoba. Cuenta con una piscina en la azotea, un gimnasio recién reformado y un restaurante. Se halla a 600 metros de la plaza San Martín y sirve desayunos. ', '3', '6', '-31.410753367662306', '-64.18470890160575', '30');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('Casa Alberdi', '966 Sipe Sipe, Córdoba, Argentina', 'La Casa Alberdi ofrece jardín y aire acondicionado y se encuentra en Córdoba, a 3,8 km del centro comercial Patio Olmos y a 4 km de la plaza de España. Esta casa dispone de aparcamiento privado gratuito, recepción 24 horas y conexión WiFi gratuita.', '4', '6', '-31.540406267025237', '-68.53014071509523', '31');
INSERT INTO `digital_booking_db`.`productos`(Nombre, Direccion, Descripcion, Categoria_ID, Ciudad_ID, Latitud, Longitud, Politica_id) VALUES('RIO y VERDE', 'Intendente Ramon Bautista Mestre 4190, 5009 Córdoba, Argentina', 'El RIO y VERDE se encuentra en Córdoba, a 2,3 km del centro comercial Córdoba y a 6 km del estadio de fútbol Mario Alberto Kempes, y ofrece piscina exterior de temporada y aire acondicionado.', '4', '6', '-31.950103398506233', '-65.05408849007746', '32');